### PR TITLE
docs: [integ-doc] upgrading the framework

### PR DESCRIPTION
**Pull request by boolafish**
### Note
- Add documentation on the part of `upgrading the framework`.

### CODE REVIEW

**Comment by boolafish** [comment]
@jarindr I added you as a random reviewer to make sure I don't write doc that only our teams understand XDDD

**Comment by cduangprom** [comment]
> @boolafish this looks good. There are a few grammatical errors, but @cduangprom is currently reviewing the entire integration doc, so let's get this part merged so that she can include it.

@kevsul and @boolafish it's my last day today. If you'd like me to update the markdown file with the changes I made so devs can add to it going forward, please let me know asap. This is the latest edited version https://docs.google.com/document/d/10ncmCFBhqGCKCilkwuA58BQYQThTlZyWW-EE_LUJnHg/edit#

**Comment by boolafish** [comment]
@cduangprom thanks for all the effort you've done!
I will merge this now, so if you still got some capacity today can you please add this part to the google file as well? Great thanks!

**Comment by cduangprom** [comment]
@boolafish 
Shouldn't I just update the markdown file?

**Comment by boolafish** [comment]
ah...okay I might have misunderstood your previous sentence. Yes markdown file is what should be done. Sorry for that ><

**Comment by cduangprom** [comment]
OK, will take a look at the latest version with your update and make the changes from the style/formatting point of view. So next version you all collaborate on should then be the edited doc

**Pull request merged**
