### PR TITLE
chore: upgrade truffle

### LINKED ISSUE #592: Upgrade truffle to newer version
## Description
Seems like truffle new release [5.1.15](https://github.com/trufflesuite/truffle/releases/tag/v5.1.15?utm_campaign=Built%20with%20Truffle&utm_source=hs_email&utm_medium=email&utm_content=84023637&_hsenc=p2ANqtz-8VD5nB54mLkQuL8aKkZAAWhGE6a4IWFR9Nvc6f2Ty6lAMA_ljIesWEy4qS9R8jDXZhdP4lWpU1vVEywhEyo1J1n9h6bA&_hsmi=84023637) might solve the previous unstable migration issue:

In this PR: https://github.com/trufflesuite/truffle/pull/2808 of the change log, it claims to solve: https://github.com/trufflesuite/truffle/issues/2257

Should give it a try and make our DevOps happy 😛

### PR DESCRIPTION
**Pull request by boolafish**
### Note
- upgrade truffle version and run `npm install`
- run `npm audit`
- fix python linter issue, probably due to flake8 upgrade.

closes #592

### CODE REVIEW

**Comment by jbunce** [comment]
Have you or the CI tried deploying contracts with this new version? We were seeing the same on Ropsten as Mainnet so that may be a good place to test.

**Comment by boolafish** [comment]
@jbunce sadly no. Current CI setup ends on a local ganache.

**Comment by jbunce** [comment]
Mind trying it out? Just that we need this tooling working now. Cc @arthurk

**Comment by boolafish** [comment]
@jbunce sure, I will do a manual sanity check first tomorrow in Rosten.

As I am in gold team this week, I will also see if I can prioritize automate this into CI. But I think it might be better in different PR to not block you guys.

**Comment by jbunce** [comment]
Yeah separate PR is fine.

**Comment by boolafish** [comment]
Sanity checked! deployed to Ropsten with some hacky address (being lazy so using one and only one address for deployer, authority and maintainer)

Deploy result
```zsh
▶ npx truffle migrate --network remote   

Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.



Starting migrations...
======================
> Network name:    'remote'
> Network id:      3
> Block gas limit: 8000029 (0x7a121d)


10_initial_checks_and_migrations.js
===================================
Deployer address: 0x9c7Fc8601655B4E1eF395107217E6eD600F7ba48
Maintainer address: 0x9c7Fc8601655B4E1eF395107217E6eD600F7ba48
Authority address: 0x9c7Fc8601655B4E1eF395107217E6eD600F7ba48
maintainer already has 1 ETH, skipping funding.
authority already has 1 ETH, skipping funding.
Deployer contains 1 ETH
Maintainer contains 1 ETH
Authority contains 1 ETH

########################### Notice ############################
It is recommended to have 0.2 ETH in the maintainer and authority address
With 1.0 ETH in the deployer address
Otherwise the deployement might fail
###############################################################


   Deploying 'Migrations'
   ----------------------
   > transaction hash:    0x332f79ab391a133f6a8ed7d6dd2b2de880751e4957537a7ffe0119aaeb7051e6
   > Blocks: 1            Seconds: 21
   > contract address:    0x1feD9558fF41BF6c3c56e64fDC88Ccc2B0E9d48d
   > block number:        7941497
   > block timestamp:     1590033949
   > account:             0x9c7Fc8601655B4E1eF395107217E6eD600F7ba48
   > balance:             0.99663428
   > gas used:            168286 (0x2915e)
   > gas price:           20 gwei
   > value sent:          0 ETH
   > total cost:          0.00336572 ETH


   > Saving migration to chain.
   > Saving artifacts
   -------------------------------------
   > Total cost:          0.00336572 ETH


20_deploy_plasma_framework.js
=============================

   Deploying 'PlasmaFramework'
   ---------------------------
   > transaction hash:    0xc138c966ec31db68a8b3c2177417879d0298716346b708945d4aaec933f7b9a2
   > Blocks: 1            Seconds: 5
   > contract address:    0xa4B94C9666BAFBFFF255BB2b51d996EF5CCa5E96
   > block number:        7941502
   > block timestamp:     1590034008
   > account:             0x9c7Fc8601655B4E1eF395107217E6eD600F7ba48
   > balance:             0.92634934
   > gas used:            3471968 (0x34fa60)
   > gas price:           20 gwei
   > value sent:          0 ETH
   > total cost:          0.06943936 ETH


   > Saving migration to chain.
   > Saving artifacts
   -------------------------------------
   > Total cost:          0.06943936 ETH


30_deploy_and_register_eth_vault.js
===================================

   Deploying 'EthDepositVerifier'
   ------------------------------
   > transaction hash:    0xbfc55e8a21c84bcb9efae8ce0b473528eb35d13d1900c176644212b27af6e9c8
   > Blocks: 2            Seconds: 21
   > contract address:    0x82562596123fEA8bA40d08c7e1Fb222fE3Bb2e38
   > block number:        7941512
   > block timestamp:     1590034134
   > account:             0x9c7Fc8601655B4E1eF395107217E6eD600F7ba48
   > balance:             0.89569092
   > gas used:            1415410 (0x1598f2)
   > gas price:           20 gwei
   > value sent:          0 ETH
   > total cost:          0.0283082 ETH


   Deploying 'EthVault'
   --------------------
   > transaction hash:    0x6e082246b6221635ee7e90c06a836db194f1cae0100a150092649190894d0a1c
   > Blocks: 1            Seconds: 17
   > contract address:    0x1a780624a2C574cb0d53309B6e53a5fF296d7598
   > block number:        7941514
   > block timestamp:     1590034162
   > account:             0x9c7Fc8601655B4E1eF395107217E6eD600F7ba48
   > balance:             0.87574308
   > gas used:            997392 (0xf3810)
   > gas price:           20 gwei
   > value sent:          0 ETH
   > total cost:          0.01994784 ETH


   > Saving migration to chain.
   > Saving artifacts
   -------------------------------------
   > Total cost:          0.04825604 ETH


40_deploy_and_register_erc20_vault.js
=====================================

   Deploying 'Erc20DepositVerifier'
   --------------------------------
   > transaction hash:    0x08706644a08d3b729d30f3d71c4614982f52776f6ea25a6231ca8a68ff1eb5ca
   > Blocks: 3            Seconds: 17
   > contract address:    0x26b3354A66612ab376815D80535dfcd70484eA8A
   > block number:        7941523
   > block timestamp:     1590034343
   > account:             0x9c7Fc8601655B4E1eF395107217E6eD600F7ba48
   > balance:             0.84322164
   > gas used:            1474708 (0x168094)
   > gas price:           20 gwei
   > value sent:          0 ETH
   > total cost:          0.02949416 ETH


   Deploying 'Erc20Vault'
   ----------------------
   > transaction hash:    0x0f0a542045174ff34a44bfa65ff441a268a9e1c35320da5987b1c1a5e06ea463
   > Blocks: 1            Seconds: 21
   > contract address:    0xc17058AEfA51c435823334E6678F9E25BC19Fa4a
   > block number:        7941525
   > block timestamp:     1590034364
   > account:             0x9c7Fc8601655B4E1eF395107217E6eD600F7ba48
   > balance:             0.82152652
   > gas used:            1084756 (0x108d54)
   > gas price:           20 gwei
   > value sent:          0 ETH
   > total cost:          0.02169512 ETH


   > Saving migration to chain.
   > Saving artifacts
   -------------------------------------
   > Total cost:          0.05118928 ETH


50_deploy_spending_condition_registry.js
========================================

   Deploying 'SpendingConditionRegistry'
   -------------------------------------
   > transaction hash:    0xe3114c0bd61362fae260aa4bb79d95299f1721790f92d00c295f86d172a8d6c5
   > Blocks: 1            Seconds: 25
   > contract address:    0xE11cFC4d6c502678AD8e0FFC80ae5F6CC2669ee7
   > block number:        7941536
   > block timestamp:     1590034510
   > account:             0x9c7Fc8601655B4E1eF395107217E6eD600F7ba48
   > balance:             0.81043258
   > gas used:            418356 (0x66234)
   > gas price:           20 gwei
   > value sent:          0 ETH
   > total cost:          0.00836712 ETH


   > Saving migration to chain.
   > Saving artifacts
   -------------------------------------
   > Total cost:          0.00836712 ETH


60_spending_conditions_payment.js
=================================

   Deploying 'PaymentOutputToPaymentTxCondition'
   ---------------------------------------------
   > transaction hash:    0xbc8055177f83f552797c0e42d65de016a78cce2826910ebe292da26b0b021202
   > Blocks: 2            Seconds: 46
   > contract address:    0xa9551c6A4DeBBAEC3A71CD17359dDb4b6351f214
   > block number:        7941541
   > block timestamp:     1590034608
   > account:             0x9c7Fc8601655B4E1eF395107217E6eD600F7ba48
   > balance:             0.76923706
   > gas used:            2032497 (0x1f0371)
   > gas price:           20 gwei
   > value sent:          0 ETH
   > total cost:          0.04064994 ETH

Registering paymentToPaymentCondition (0xa9551c6A4DeBBAEC3A71CD17359dDb4b6351f214) to spendingConditionRegistry

   Replacing 'PaymentOutputToPaymentTxCondition'
   ---------------------------------------------
   > transaction hash:    0xf969a1688f2fea7b30d8505c3dc2ae841ee777cf9f5b6a8bf9e5c0bfc0b87293
   > Blocks: 3            Seconds: 45
   > contract address:    0xbD766D9368Bf63eC43057Fc9c0ce34674e06Ee2e
   > block number:        7941547
   > block timestamp:     1590034691
   > account:             0x9c7Fc8601655B4E1eF395107217E6eD600F7ba48
   > balance:             0.72767308
   > gas used:            2032497 (0x1f0371)
   > gas price:           20 gwei
   > value sent:          0 ETH
   > total cost:          0.04064994 ETH

Registering paymentToPaymentV2Condition (0xbD766D9368Bf63eC43057Fc9c0ce34674e06Ee2e) to spendingConditionRegistry

   > Saving migration to chain.
   > Saving artifacts
   -------------------------------------
   > Total cost:          0.08129988 ETH


61_spending_conditions_fee.js
=============================

   Deploying 'FeeClaimOutputToPaymentTxCondition'
   ----------------------------------------------
   > transaction hash:    0xc54a79d3941689f5391e0bdb9d1503555c7a18792bb4005a3a81347394b47d37
   > Blocks: 1            Seconds: 21
   > contract address:    0xFF5BeF40D8441453e8c041C77BcEf8b74c7333e0
   > block number:        7941554
   > block timestamp:     1590034778
   > account:             0x9c7Fc8601655B4E1eF395107217E6eD600F7ba48
   > balance:             0.68278462
   > gas used:            2171442 (0x212232)
   > gas price:           20 gwei
   > value sent:          0 ETH
   > total cost:          0.04342884 ETH

Registering feeClaimOutputToPaymentTxCondition (0xFF5BeF40D8441453e8c041C77BcEf8b74c7333e0) to spendingConditionRegistry

   > Saving migration to chain.
   > Saving artifacts
   -------------------------------------
   > Total cost:          0.04342884 ETH


99_renounce_spending_condition_registry.js
==========================================

   > Saving migration to chain.
   -------------------------------------
   > Total cost:                   0 ETH


100_payment_standard_controllers.js
===================================

   Deploying 'PaymentStartStandardExit'
   ------------------------------------
   > transaction hash:    0xd8986ad42380179ad6e6f76fa3399c6d5d2872291cde7a0de52f5b9baf9e2080
   > Blocks: 1            Seconds: 21
   > contract address:    0x63784Bc1D93bF4450EffE6E60c9baB483Aa0a346
   > block number:        7941566
   > block timestamp:     1590034972
   > account:             0x9c7Fc8601655B4E1eF395107217E6eD600F7ba48
   > balance:             1.42510662
   > gas used:            2768384 (0x2a3e00)
   > gas price:           20 gwei
   > value sent:          0 ETH
   > total cost:          0.05536768 ETH


   Deploying 'PaymentChallengeStandardExit'
   ----------------------------------------
   > transaction hash:    0x29a3b1a062150ecf28f80bcb295c78c840c7b73897474adcbf3cd6d49bc41900
   > Blocks: 3            Seconds: 65
   > contract address:    0x566436Af2DcAd2157073B2636239e60D1dfb930A
   > block number:        7941569
   > block timestamp:     1590035028
   > account:             0x9c7Fc8601655B4E1eF395107217E6eD600F7ba48
   > balance:             1.37898882
   > gas used:            2305890 (0x232f62)
   > gas price:           20 gwei
   > value sent:          0 ETH
   > total cost:          0.0461178 ETH


   Deploying 'PaymentProcessStandardExit'
   --------------------------------------
   > transaction hash:    0x5a0cb8b94300fa0ccc4974b0d45dc56e1ea0ecabbf8b1e5f236e25c5e15baad0
   > Blocks: 2            Seconds: 105
   > contract address:    0xC902586c8B79731BA49c0E51F75130d26E1391fd
   > block number:        7941572
   > block timestamp:     1590035163
   > account:             0x9c7Fc8601655B4E1eF395107217E6eD600F7ba48
   > balance:             1.3697454
   > gas used:            462171 (0x70d5b)
   > gas price:           20 gwei
   > value sent:          0 ETH
   > total cost:          0.00924342 ETH


   > Saving migration to chain.
   > Saving artifacts
   -------------------------------------
   > Total cost:           0.1107289 ETH


110_payment_ife_controllers.js
==============================

   Deploying 'PaymentStartInFlightExit'
   ------------------------------------
   > transaction hash:    0x6968c9f5f2bcf6a1adf109960e74b7f13dbd9e9b0568edbf8053075e4a28b906
   > Blocks: 1            Seconds: 17
   > contract address:    0x12A7aADc584CDaA163b331E5fc512f8C6e5ea74C
   > block number:        7941576
   > block timestamp:     1590035240
   > account:             0x9c7Fc8601655B4E1eF395107217E6eD600F7ba48
   > balance:             1.3018961
   > gas used:            3365186 (0x335942)
   > gas price:           20 gwei
   > value sent:          0 ETH
   > total cost:          0.06730372 ETH


   Deploying 'PaymentPiggybackInFlightExit'
   ----------------------------------------
   > transaction hash:    0xf72573f6084284221101d0dfdb3b39e4f1dfc940ccfb63e1ae4d4d0f17c47cfd
   > Blocks: 1            Seconds: 21
   > contract address:    0xd3CCb37eC70A5519D8BeAa728e101Bd2c5f7Bd4b
   > block number:        7941578
   > block timestamp:     1590035258
   > account:             0x9c7Fc8601655B4E1eF395107217E6eD600F7ba48
   > balance:             1.26504208
   > gas used:            1842701 (0x1c1e0d)
   > gas price:           20 gwei
   > value sent:          0 ETH
   > total cost:          0.03685402 ETH


   Deploying 'PaymentChallengeIFENotCanonical'
   -------------------------------------------
   > transaction hash:    0xd797b96972c65829173889f9194db6bd7b597a2dcd660193aea31c5cbc33ad20
   > Blocks: 2            Seconds: 17
   > contract address:    0x4d3a0B88Cc9A904BA629bD7E6986618945Fba52d
   > block number:        7941581
   > block timestamp:     1590035306
   > account:             0x9c7Fc8601655B4E1eF395107217E6eD600F7ba48
   > balance:             1.21221376
   > gas used:            2641416 (0x284e08)
   > gas price:           20 gwei
   > value sent:          0 ETH
   > total cost:          0.05282832 ETH


   Deploying 'PaymentChallengeIFEInputSpent'
   -----------------------------------------
   > transaction hash:    0xe4a021a777a21b5b33f83f47097ed95182d87d571ff01ca68f3d0ce5ab974eff
   > Blocks: 1            Seconds: 13
   > contract address:    0x42758Bc2c9763EA1FbE7e4f45a4f1CF6560f45f5
   > block number:        7941583
   > block timestamp:     1590035328
   > account:             0x9c7Fc8601655B4E1eF395107217E6eD600F7ba48
   > balance:             1.16639126
   > gas used:            2291125 (0x22f5b5)
   > gas price:           20 gwei
   > value sent:          0 ETH
   > total cost:          0.0458225 ETH


   Deploying 'PaymentChallengeIFEOutputSpent'
   ------------------------------------------
   > transaction hash:    0x4b2b4c7ce3c58ec7df6ccdd4da0024b4d8938136535acdfadf6581e019de4e53
   > Blocks: 0            Seconds: 9
   > contract address:    0xa462469dC23DebF8e81030c57D15d0A33f230Bd6
   > block number:        7941586
   > block timestamp:     1590035353
   > account:             0x9c7Fc8601655B4E1eF395107217E6eD600F7ba48
   > balance:             1.1213287
   > gas used:            2253128 (0x226148)
   > gas price:           20 gwei
   > value sent:          0 ETH
   > total cost:          0.04506256 ETH


   Deploying 'PaymentDeleteInFlightExit'
   -------------------------------------
   > transaction hash:    0x90329cf4f79dfed7cac56fb6a54a39f94add17dc0439d8dab3e90b59a5a6151b
   > Blocks: 1            Seconds: 27
   > contract address:    0xe5178Be3987ae4535f5D30568dF1400633EcB736
   > block number:        7941588
   > block timestamp:     1590035388
   > account:             0x9c7Fc8601655B4E1eF395107217E6eD600F7ba48
   > balance:             1.1089822
   > gas used:            617325 (0x96b6d)
   > gas price:           20 gwei
   > value sent:          0 ETH
   > total cost:          0.0123465 ETH


   Deploying 'PaymentProcessInFlightExit'
   --------------------------------------
   > transaction hash:    0x37a90d8ad03945847b8d116f8bc5b84a878a9cc90fc0949cdbe432e3e0cd404e
   > Blocks: 2            Seconds: 41
   > contract address:    0x1c8075078F224199264a3DFfEb2c3dFc97BA6C46
   > block number:        7941591
   > block timestamp:     1590035430
   > account:             0x9c7Fc8601655B4E1eF395107217E6eD600F7ba48
   > balance:             1.77067712
   > gas used:            1915254 (0x1d3976)
   > gas price:           20 gwei
   > value sent:          0 ETH
   > total cost:          0.03830508 ETH


   > Saving migration to chain.
   > Saving artifacts
   -------------------------------------
   > Total cost:           0.2985227 ETH


120_payment_state_transition_verifier.js
========================================

   Deploying 'PaymentTransactionStateTransitionVerifier'
   -----------------------------------------------------
   > transaction hash:    0x611792311cfdf3aa07acd8d66edc5491b74d69f476f8bc7893547320d1619808
   > Blocks: 1            Seconds: 41
   > contract address:    0x6B046560645a3017Df0f32676Bb9A3356aE71F5F
   > block number:        7941596
   > block timestamp:     1590035546
   > account:             0x9c7Fc8601655B4E1eF395107217E6eD600F7ba48
   > balance:             1.73691988
   > gas used:            1660583 (0x1956a7)
   > gas price:           20 gwei
   > value sent:          0 ETH
   > total cost:          0.03321166 ETH


   > Saving migration to chain.
   > Saving artifacts
   -------------------------------------
   > Total cost:          0.03321166 ETH


140_payment_exit_game.js
========================

   Deploying 'PaymentExitGame'
   ---------------------------
   > transaction hash:    0x6d90c0efc998d6249aff8c11f974acfcb227f4a25c7b503157722a463f906753
   > Blocks: 1            Seconds: 22
   > contract address:    0xAB219EdFb40ED87174Bdfa6EA1feDD6D87c28e63
   > block number:        7941601
   > block timestamp:     1590035594
   > account:             0x9c7Fc8601655B4E1eF395107217E6eD600F7ba48
   > balance:             1.64959712
   > gas used:            4338859 (0x4234ab)
   > gas price:           20 gwei
   > value sent:          0 ETH
   > total cost:          0.08677718 ETH


   > Saving migration to chain.
   > Saving artifacts
   -------------------------------------
   > Total cost:          0.08677718 ETH


200_fee_exit_game.js
====================

   Deploying 'FeeExitGame'
   -----------------------
   > transaction hash:    0x1df6c5332d10b5ed7d8aed80fd01c9329d16109d224c88d093c37cfb7386a2fe
   > Blocks: 1            Seconds: 33
   > contract address:    0x7d5C583297484Ed986AF3cb126fdb6acAD469400
   > block number:        7941608
   > block timestamp:     1590035663
   > account:             0x9c7Fc8601655B4E1eF395107217E6eD600F7ba48
   > balance:             1.64576394
   > gas used:            66850 (0x10522)
   > gas price:           20 gwei
   > value sent:          0 ETH
   > total cost:          0.001337 ETH


   > Saving migration to chain.
   > Saving artifacts
   -------------------------------------
   > Total cost:            0.001337 ETH


300_payment_v2_spending_condition_registry.js
=============================================

   > Saving migration to chain.
   -------------------------------------
   > Total cost:                   0 ETH


301_payment_v2_spending_conditions.js
=====================================

   > Saving migration to chain.
   -------------------------------------
   > Total cost:                   0 ETH


302_renounce_payment_v2_spending_condition_registery.js
=======================================================

   > Saving migration to chain.
   -------------------------------------
   > Total cost:                   0 ETH


303_payment_v2_exit_game.js
===========================

   > Saving migration to chain.
   -------------------------------------
   > Total cost:                   0 ETH


1010_tenderly_setup.js
======================

   > Saving migration to chain.
   -------------------------------------
   > Total cost:                   0 ETH


1020_deploy_dev_contracts.js
============================

   > Saving migration to chain.
   -------------------------------------
   > Total cost:                   0 ETH


1030_output_results.js
======================
{"authority_address":"0x9c7fc8601655b4e1ef395107217e6ed600f7ba48","eth_vault":"0x1a780624a2c574cb0d53309b6e53a5ff296d7598","erc20_vault":"0xc17058aefa51c435823334e6678f9e25bc19fa4a","payment_exit_game":"0xab219edfb40ed87174bdfa6ea1fedd6d87c28e63","plasma_framework_tx_hash":"0xc138c966ec31db68a8b3c2177417879d0298716346b708945d4aaec933f7b9a2","plasma_framework":"0xa4b94c9666bafbfff255bb2b51d996ef5cca5e96"}

   > Saving migration to chain.
   -------------------------------------
   > Total cost:                   0 ETH


Summary
=======
> Total deployments:   23
> Final cost:          0.83592368 ETH

```

**Pull request merged**
