### PR TITLE
Review Address.md

### PR DESCRIPTION
**Pull request by cduangprom**
First review of these files, need to clarify some of the content. Questions in comments.

### CODE REVIEW

**Comment by boolafish** [comment]
I haven’t fully take into the PR yet, but all doc here is auto generated via code document. And sadly this Address file is actually from open zeppelin which we don’t have control. ( we use it as dependency and the doc gen tool pulled that in too)

**Comment by cduangprom** [comment]
@boolafish I'm aware the doc is auto-generated, that's fine, but can the output seen in the .md file be edited? Gerhard requested I review these files for language and formatting. He said I could edit and create the PR. The first PR is exploratory, thus my questions. Are the doc files in this repo the final output to show to audience?

**Comment by cduangprom** [comment]
Somehow the pr closed with my last comment

**Comment by cduangprom** [comment]
@boolafish Gerhard has just advised I should take a look at source files instead, in the code at https://github.com/omisego/plasma-contracts/tree/master/plasma_framework/contracts/src.

**Comment by boolafish** [comment]
Oh yeah, if any change you’d like to make should be on source code directly. Just sadly the file edited in this PR it is out of our control

**Comment by cduangprom** [comment]
@boolafish latest natspec format is now v0.5.12. Will you continue with v0.5.11 or will the auto-generate automatically apply v0.5.12 when you next generate docs. I'm sure minor differences only just want to check

**Pull request closed without merging**
