### PR TITLE
feat: rename 'token' to 'ercContract' in framework

### PR DESCRIPTION
**Pull request by boolafish**
### Note
We are renaming 'token' to 'ercContract' as the word 'token' might not be appropriate when it is
not using for ERC20 tokens on `PlasmaFramework`.

closes issue: https://github.com/omisego/plasma-contracts/issues/273

(PS. if anyone has better naming idea please let me know)

### CODE REVIEW

**Comment by pdobacz** [comment]
> (PS. if anyone has better naming idea please let me know)

I don't, but `ercContract` is bothering me too :(. I was thinking `currency` - which is what we use interchangeably (sigh) in code. Maybe a native English speaker could weigh in on how bad it sounds in the context of an ERC721 contract.

But please, consider keeping it to "Token", c.f. https://etherscan.io/token/0x06012c8cf97bead5deae237070f9587f8e7a266d and https://etherscan.io/tokens-nft

they're both using "token" in the context of the ERC721 contract, and "tokenID" for individual items. I think it is perfectly acceptable even if not strictly correct.

BTW, Is there input from anyone who actually was confused by use of the term "token" or are we just future proofing here?

**Comment by boolafish** [comment]
> BTW, Is there input from anyone who actually was confused by use of the term "token" or are we just future proofing here?

Just future proofing I guess. 

> But please, consider keeping it to "Token", c.f. https://etherscan.io/token/0x06012c8cf97bead5deae237070f9587f8e7a266d and https://etherscan.io/tokens-nft

Oh nice, I was keep wondering how people handle ERC721 contract. I wasn't able to find the word from the ERC implementation.

If they are others using `token`, then sure I don't have strong opinion. I think something from @paulperegud 's recent writing might be a good one: `token_contract_address` so we don't confuse with what it really means. How do you think @pdobacz ?


Btw, this issue/PR is only targeting the renaming on framework layer as `token` still makes perfect sense to the `PaymentTx` and it's clear and simple enough there so I am not proposing to change that. It is just on the framework layer it would be confusing as it is really the ERC contract address and the reason of having that in framework is really just to isolate the exit queue for external contracts.

**Comment by pdobacz** [comment]
`token_contract_address` is quite long and still can be just as confusing, if someone isn't fully aware of how ERC721 is constructed ("since it's called token_contract_address, do individual items have their contract addresses, huh?")

I don't have a strong opinion either, but the pragmatic side of things is:
 - let's be lax on this
 - let's be good to ourselves and avoid long names for things (we'll probably still be saying "token" in our conversations...)
 - let's not change stuff that settled in, if there's no strong reasons to do so ;)
 - etherscan is kinda source of truth and strong reference, consistency with that will help.

But no strong opinion here too, in the end. Maybe let's not bikeshed and just toss a coin :)

**Comment by boolafish** [comment]
okay, in general I am convinced that `token` might be able to be enough for a good enough while. Though personally I do hope to make it something like `tokenContract` at least so we'd know it's really talking about the external contract from framework's point of view.

btw, I haven't dig into this deep yet but there do is sth like this: https://blog.enjincoin.io/erc-1155-the-final-token-standard-on-ethereum-a83fce9f5714 which has multiple token protocol under one contract (ouch....). Anyway, we might never tough that anyway XD

**Comment by boolafish** [comment]
close this in flavor of #285 and stick with name `token`.

**Pull request closed without merging**
