### PR TITLE
269 migration script

### PR DESCRIPTION
**Pull request by boolafish**
Currently a draft to show what's the ordering of deployment and registration would be like.

One issue I see when writing this migration:
The contract is designed to re-use in the future. As a result, we might need to deploy one contract with potentially different args multiple times in the future. However, truffle migration using  `deployer.deployed(ContractName)` might not be able to differentiate multiple deployment. https://github.com/trufflesuite/truffle/issues/237

Potentially we can probably use `new` for the contracts that has the possibility to re-deploy?

### CODE REVIEW

**Comment by boolafish** [comment]
@kendricktan here's the draft! BTW, current contract would exceed normal gas size so I use 8000000 for now. If you'd like to try, please initiate instance with higher gas.

cc @thec00n as you might be interested in migration script.

**Comment by thec00n** [comment]
@boolafish @kendricktan Could we consider the following as part of this PR:

- Fix the version of `openzeppelin-solidity` to 2.3.0 and manually upgrade. The contracts are injected in various parts of the contract system. It is safer to chose a manual upgrade path in this case. 
- Fix the version of the Solidity compiler 0.5.11. Consider to fix the pragma version in the contracts as well. 
- Decide if the contracts are deployed with optimizations. If so let's set the option by default and make sure that all tests run in an environment with optimizations set.

**Comment by kendricktan** [comment]
@thec00n 

- (Y) How are you injecting `openzepplin-solidity`? From the looks of it it just seems like you're loading it from `node_modules`
- (Y)
- (Y) It'll need to be run with optimizations otherwise it'll keep throwing the `gas required exceeds allowance` error

**Comment by thec00n** [comment]
> @thec00n
> 
> * 👍  How are you injecting `openzepplin-solidity`? From the looks of it it just seems like you're loading it from `node_modules`

I think truffle takes care of looking in the right place when it compiles the contracts.

**Comment by kendricktan** [comment]
@thec00n even with optimizations, the gas limit still exceeds the allowance. Any ideas? :\

**Comment by thec00n** [comment]
@boolafish or @kevsul might know?

**Comment by pdobacz** [comment]
@kendricktan Sorry to jump in, but maybe this will help:

> even with optimizations, the gas limit still exceeds the allowance. Any ideas? :\

If we're talking about exceeding the allowance on contract deployment, try optimizations on but with 1 run. This works for me (at least for a subset of the required deployments).

1 run optimizes for compactness of the bytecode, thereby minimizing the deployment gas cost

**Comment by kevsul** [comment]
If you switch on optimisations, be aware of this issue: https://github.com/omisego/plasma-contracts/issues/286
Deleting `PaymentStandardExitRouterMock.sol` work around it for now.

With that I've been able to deploy to Rinkeby. I've had to add an explicit `{ gas: 6500000 }` when deploying `PaymentExitGame` as well.

**Comment by boolafish** [comment]
Do we really need to base on the `150_python_tests_on_plasma_framework` branch? BTW, why elixir uses that branch instead of master @pdobacz ? Also, if it's necessary to base on that branch, can @pik694 find a point that we can merge the PR first? and we keep on migrate other python codes with other PRs so we don't block ourselves or doing code review cross PRs.

**Comment by kasima** [comment]
Agree with @boolafish here. If we need to wait for that branch, let's merge it first so things don't get too messy.

**Comment by kendricktan** [comment]
@kasima @boolafish so should I cull the merges and restart migrations from master in this case?

**Comment by boolafish** [comment]
hmmm probably, if it's not too hard to move back to master (?)
Also, I am still not following why we need to do it on top of the python test branch

**Comment by pik694** [comment]
I will rebase today and try to prepare a PR :)

**Comment by pdobacz** [comment]
> BTW, why elixir uses that branch instead of master @pdobacz ?

b/c I'm integrating elixir to what I know works with the old python tests, so I know how things might break and what part of contract functionality I can rely on.

+1 on merging what's mergable to `plasma-contracts/master` in general and moving on.

**Comment by kasima** [comment]
Thanks for untangling these dependencies, everyone. 🙌

**Pull request closed without merging**
